### ISSUE TITLE
Fail if duplicate keys exist in one file

### ISSUE THREAD

**Issue by amire80** [wikimedia/banana-checker#22]
Quick googling says that the JSON standard doesn't forbid duplicate keys, but this definitely shouldn't happen in one messages file. This already happened in a commit at least once and should be checked.

(Whether keys can repeat in two different files en.json files is a separate question.)

**Comment by Krinkle** [comment]
See also https://github.com/zaach/jsonlint/issues/13.

**Comment by legoktm** [comment]
https://bugzilla.wikimedia.org/show_bug.cgi?id=71284 is related.

**Comment by Krinkle** [comment]
Closing in favour of https://github.com/wikimedia/eslint-config-wikimedia/issues/166.
